### PR TITLE
fix: more gently quit eventsub thread

### LINKED ISSUE #5796: Chatterino hanging in background on close (macOS)
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

I'm running a slightly old build (4f1a0ad5). I closed chatterino (or so I thought) until I saw it was still running in the background at 100% CPU usage with no windows opened. Killing the process yielded the following stack trace:

```
Heaviest stack for the main thread of the target process:
  17  start + 2360 (dyld + 24800) [0x181e3d0e0]
  17  main + 4092 (chatterino + 4938556) [0x101255b3c]
  17  chatterino::runGui(QApplication&, chatterino::Paths const&, chatterino::Settings&, chatterino::Args const&, chatterino::Updates&) + 1952 (chatterino + 4048828) [0x10117c7bc]
  17  chatterino::Application::~Application() + 168 (chatterino + 1322424) [0x100ee2db8]
  17  chatterino::SeventvEventAPI::~SeventvEventAPI() + 12 (chatterino + 431408) [0x100e09530]
  17  chatterino::SeventvEventAPI::~SeventvEventAPI() + 1756 (chatterino + 430988) [0x100e0938c]
  17  std::__1::__tree<std::__1::__value_type<std::__1::weak_ptr<void>, std::__1::shared_ptr<chatterino::BasicPubSubClient<chatterino::seventv::eventapi::Subscription>>>, std::__1::__map_value_compare<std::__1::weak_ptr<void>, std::__1::__value_type<std::__1::weak_ptr<void>, std::__1::shared_ptr<chatterino::BasicPubSubClient<chatterino::seventv::eventapi::Subscription>>>, std::__1::owner_less<std::__1::weak_ptr<void>>, true>, std::__1::allocator<std::__1::__value_type<std::__1::weak_ptr<void>, std::__1::shared_ptr<chatterino::BasicPubSubClient<chatterino::seventv::eventapi::Subscription>>>>>::destroy(std::__1::__tree_node<std::__1::__value_type<std::__1::weak_ptr<void>, std::__1::shared_ptr<chatterino::BasicPubSubClient<chatterino::seventv::eventapi::Subscription>>>, void*>*) + 76 (chatterino + 4878780) [0x1012471bc]
  17  chatterino::seventv::eventapi::Client::~Client() + 80 (chatterino + 4892108) [0x10124a5cc]
  17  boost::asio::detail::io_object_impl<boost::asio::detail::deadline_timer_service<boost::asio::detail::chrono_time_traits<std::__1::chrono::steady_clock, boost::asio::wait_traits<std::__1::chrono::steady_clock>>>, boost::asio::any_io_executor>::~io_object_impl() + 56 (chatterino + 1671244) [0x100f3804c]
  17  boost::asio::detail::io_object_impl<boost::asio::detail::deadline_timer_service<boost::asio::detail::chrono_time_traits<std::__1::chrono::steady_clock, boost::asio::wait_traits<std::__1::chrono::steady_clock>>>, boost::asio::any_io_executor>::~io_object_impl() + 56 (chatterino + 1671244) [0x100f3804c]
  17  _sigtramp + 56 (libsystem_platform.dylib + 14884) [0x1821eda24]
  15  chatterino::(anonymous namespace)::handleSignal(int) + 88 (chatterino + 4057840) [0x10117eaf0]
 *15  ??? (kernel.release.t8103 + 31592) [0xfffffe000851fb68]
 *14  ??? (kernel.release.t8103 + 1712408) [0xfffffe00086ba118]
 *13  ??? (kernel.release.t8103 + 1715872) [0xfffffe00086baea0]
 *12  ??? (kernel.release.t8103 + 374408) [0xfffffe0008573688]
 *12  ??? (kernel.release.t8103 + 372748) [0xfffffe000857300c]
 *12  ??? (kernel.release.t8103 + 912384) [0xfffffe00085f6c00]
 *6   ??? (kernel.release.t8103 + 399112) [0xfffffe0008579708]
 *6   ??? (kernel.release.t8103 + 208340) [0xfffffe000854add4]
 *2   ??? (kernel.release.t8103 + 393036) [0xfffffe0008577f4c]
```

Poking around, I don't exactly know what's going on with the EventAPI but was thinking this could be a possible solution:
```diff
diff --git a/src/providers/liveupdates/BasicPubSubClient.hpp b/src/providers/liveupdates/BasicPubSubClient.hpp
index aa65e619..a1bfe706 100644
--- a/src/providers/liveupdates/BasicPubSubClient.hpp
+++ b/src/providers/liveupdates/BasicPubSubClient.hpp
@@ -42,7 +42,13 @@ public:
     {
     }

-    virtual ~BasicPubSubClient() = default;
+    virtual ~BasicPubSubClient()
+    {
+        if (this->isStarted())
+        {
+            this->stop();
+        }
+    }

     BasicPubSubClient(const BasicPubSubClient &) = delete;
     BasicPubSubClient(const BasicPubSubClient &&) = delete;
```

Unfortunately I can't seem to replicate this hang, but I'm proposing this diff in case someone sees it and says "Ah, of course we need to do that". It could also be related to some sort of signal processing going on during teardown that shouldn't be happening, given the `handleSignal` frame. I'll report back if I run into this again.

### Screenshots

_No response_

### OS and Chatterino Version

Chatterino 2.5.2-beta.1 (commit 4f1a0ad5 modified) built with Qt 6.7.3 Running on macOS Sonoma (14.2), kernel: 23.2.0

### PR DESCRIPTION
**Pull request by pajlada**
running some tests and shit atm

Fixes #5796

### CODE REVIEW

File: src/providers/twitch/eventsub/Controller.cpp [hunk 1]
```diff
@@ -81,6 +86,12 @@ Controller::~Controller()
 
     this->work.reset();
 
+    if (!this->stoppedFlag.waitFor(std::chrono::milliseconds(250)))
+    {
+        qCWarning(LOG) << "Force end";
+        return;
```
Comment (Nerixyz) [inline src/providers/twitch/eventsub/Controller.cpp:92]: This would call `std::terminate` if the thread isn't joined when it's destructed. Not sure if that's what we want. Probably depends on what else would happen afterwards.

File: src/providers/twitch/eventsub/Controller.cpp [hunk 2]
```diff
@@ -111,16 +118,22 @@ Controller::~Controller()
 
     this->work.reset();
 
-    if (this->thread->joinable())
+    if (!this->thread->joinable())
     {
-        this->thread->join();
+        qCWarning(LOG) << "Controller thread is not joinable";
+        this->thread->detach();
```
Comment (Nerixyz) [inline src/providers/twitch/eventsub/Controller.cpp]: If the thread isn't joinable, it has either been joined already or it was default constructed. See [`std::thread::joinable`](https://en.cppreference.com/w/cpp/thread/thread/joinable.html). It is specially not probing the OS if the thread is busy.

If the thread isn't joinable, there's no need to detach. The destructor will do nothing (see [`std::thread::~thread`](https://en.cppreference.com/w/cpp/thread/thread/~thread.html)).

File: src/providers/twitch/eventsub/Controller.cpp [hunk 3]
```diff
@@ -111,16 +118,22 @@ Controller::~Controller()
...
     {
-        qCWarning(LOG) << "Thread not joinable";
+        this->thread->join();
+        qCWarning(LOG) << "Controller dtor end good";
+        return;
     }
 
-    qCInfo(LOG) << "Controller dtor end";
+    qCWarning(LOG) << "Controller dtor end bad, thread didn't finish within "
+                      "250ms, detaching and letting the OS handle it";
```
Comment (Nerixyz) [inline src/providers/twitch/eventsub/Controller.cpp]: This is misleading. If the thread hasn't been joined at this point, it's still joinable (i.e. it has an associated thread), thus `std::terminate` will be called in the destructor. So after this log, Chatterino will exit.

Note: One could detach the thread here, but doing so would likely result in weird use-after-free bugs, because the thread is still doing _something_ (likely in some event loop). If some event comes in, it will likely access something that was destroyed in this destructor.

File: src/providers/twitch/eventsub/Controller.cpp (hunk 2 above)
Comment (pajlada) [reply src/providers/twitch/eventsub/Controller.cpp]: [`0f5a89f` (#6136)](https://github.com/Chatterino/chatterino2/pull/6136/commits/0f5a89fae0bd37e895ca74b7105da9c2080aece3)

File: src/providers/twitch/eventsub/Controller.cpp (hunk 3 above)
Comment (pajlada) [reply src/providers/twitch/eventsub/Controller.cpp]: meant to add detach there - fixed in [`7176359` (#6136)](https://github.com/Chatterino/chatterino2/pull/6136/commits/71763594433d27822a79e41f571fca16b435910d)

A cleaner fix would be to ensure the thread actually stops what it's doing, but as an interim fix we detach threads when we're about to quit.

Is there anything else we could do in the short-term to ensure Chatterino doesn't hang on exit?

**Review by pajlada — COMMENTED** [review]
Image
