### PR TITLE
Messages held by automod are now shown to the user

### LINKED ISSUE #2626: Messages from yourself that get caught by AutoMod don't show up in chat at all (it doesn't even tell you it was caught).
#  **Describe the bug:**  #
**Messages from yourself that get caught by AutoMod don't tell you that they were OR show up at all in the Chatterino chat client.**

#  **To reproduce:**  #
**Have a message get caught by AutoMod.**

#  **Screenshots:**  #

**Not Applicable.**

#  **Chatterino version:**  #
**Chatterino 2.2.3-beta2 (commit 59afb2b1c)**

#  **Operating system:**  #
**macOS Big Sur Version 11.2.3**

macOS Big Sur Version 11.2.3

#  **Additional information:**  #
**It should at least tell you that it was caught by AutoMod like it does in the native chat client. It doesn't even tell you that, and just doesn't post anything to chat.**

### PR DESCRIPTION
**Pull request by apa420**
Pull request checklist:

- [x] `CHANGELOG.md` was updated, if applicable

# Description
**Requires #2742**
Closes #2626
Now shows when a message is being held by automod through pubsub.

Sent two profane messages and then accepted the first and denied the second. (There are badges and stuff so it looks good but I have them disabled and forgot to enable them for this screenshot)

(I don't know why formatting failed I have clang-format version 11.1.0)

### CODE REVIEW

File: src/messages/MessageBuilder.hpp [hunk 1]
```diff
@@ -60,7 +62,7 @@ class MessageBuilder
     void addLink(const QString &origLink, const QString &matchedLink);
 
     template <typename T, typename... Args>
-    T *emplace(Args &&... args)
+    T *emplace(Args &&...args)
```
Comment (iProdigy) [inline src/messages/MessageBuilder.hpp:65]:
```suggestion
    T *emplace(Args &&... args)
```

to appease the linter

**Review by iProdigy — APPROVED** [review]

**Comment by AustinHolderr** [comment]
@apa420 thank you for your hard work into fixing this issue 💛 i appreciate it

**Review by pajlada — APPROVED** [review]
LGTM :+1:
