### PR TITLE
fix: Tooltip parenting on Windows

### LINKED ISSUE #5019: Moving over different windows' popups automatically switches focus
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

**Describe the bug**
When multiple Chatterino windows are opened and overlaid on top of each other, moving the cursor over another one's popups (hovers) will automatically move the focus over to the other window.

**To reproduce**
- Open two windows of Chatterino 
- Overlay them on top of each other partially
- Mouse over different popups (e.g. stream title, link preview, emote detail, badge detail, etc.)
- Observe windows switching focus
- Likely only observable on Windows

### Screenshots

**Video preview**
- In this video preview, I do not press any keys or any mouse buttons

https://github.com/Chatterino/chatterino2/assets/7684273/c7934cb3-607b-4e17-88ef-25888b31e47e

### OS and Chatterino Version

Chatterino Nightly 2.4.6 (commit fd4cac2c) built on 2023-12-10 with Qt 6.5.0, MSVC 193732826 Running on Windows 10 Version 22H2, kernel: 10.0.19045

### PR DESCRIPTION
**Pull request by Nerixyz**
This PR sets the parent on tooltips to be `nullptr` on Windows and deletes the tooltip when appropriate.

Fixes #5019.

### CODE REVIEW

File: src/widgets/TooltipWidget.hpp [hunk 1]
```diff
@@ -29,6 +29,11 @@ class TooltipWidget : public BaseWindow
     Q_OBJECT
 
 public:
+    /// @param parent The parent of this widget.
+    ///               If this widget is a window, use tooltipParentFor().
```
Comment (pajlada) [inline src/widgets/TooltipWidget.hpp:33]: Is this more accurate?

```suggestion
    ///               If the parent is a window, use tooltipParentFor().
```

**Review by pajlada — APPROVED** [review]
Looks good to me, just a question about the documentation before I'll merge this in

File: src/widgets/TooltipWidget.hpp (hunk 1 above)
Comment (Nerixyz) [reply src/widgets/TooltipWidget.hpp:33]: No. If we take `ChannelView` for example: `ChannelView` is not a window, but `Tooltip` is used as a window there. See [`QWidget::isWindow`](https://doc.qt.io/qt-6/qwidget.html#isWindow).

Comment (pajlada) [reply src/widgets/TooltipWidget.hpp:33]: In what scenario would we not want to use `tooltipParentFor` then?
Right now we use it both times the tooltip widget is created (`ChannelView` & `SplitHeader`)

Comment (Nerixyz) [reply src/widgets/TooltipWidget.hpp:33]: If the tooltip widget is embedded into another widget (or through multiple layers) that is then shown as a window.

Comment (pajlada) [reply src/widgets/TooltipWidget.hpp:33]: Since that's not a scenario that we run into now, let's just simplify this & expand to support those use cases as they come up.
Either just `#ifdef` in the constructor itself, or make `tooltipParentFor` a static function in the source file & use it in the constructor

**Review by pajlada — CHANGES_REQUESTED** [review]
Pending small change from discussion above

**Review by pajlada — APPROVED** [review]
