### PR TITLE
Fixed cheers not showing up in chat 

### LINKED ISSUE #1031: Bits on twitch not showing in chatterino
I have seen alot of pepole do cheer15 for example but i cant see the bit animation/gif in chatterino.

### PR DESCRIPTION
**Pull request by apa420**
Makes cheers show up in chatterino.
F7 also makes test messages appear in #pajlada.
Fixes #1031

### CODE REVIEW

**Comment by apa420** [comment]
Needs some aditional testing it seems.
Not ready for merge.

File: src/providers/twitch/TwitchChannel.hpp [hunk 1]
```diff
@@ -92,6 +92,12 @@ class TwitchChannel : public Channel, pajlada::Signals::SignalHolder
     boost::optional<EmotePtr> twitchBadge(const QString &set,
                                           const QString &version) const;
 
+    // Cheers
+    boost::optional<
+        std::tuple<boost::optional<EmotePtr>, boost::optional<EmotePtr>,
+                   boost::optional<QColor>>>
```
Comment (pphop) [inline src/providers/twitch/TwitchChannel.hpp]: Could just use [CheerEmote](https://github.com/Chatterino/chatterino2/blob/master/src/providers/twitch/TwitchEmotes.hpp#L18) instead of a tuple 😄

**Comment by apa420** [comment]
Now also displays the right tier of cheer type (like 10000 cheer emote).
Also added some extra test.
It seems like the subway emotes are some special thing, so I don't know if it's possible to add them.

File: src/providers/twitch/TwitchChannel.cpp [hunk 2]
```diff
@@ -739,22 +739,22 @@ void TwitchChannel::refreshBadges()
...
+                    weak = weakOf<Channel>(this)](auto result) -> Outcome {
             auto cheerEmoteSets = ParseCheermoteSets(result.parseRapidJson());
             std::vector<CheerEmoteSet> emoteSets;
 
-            for (auto &set : cheerEmoteSets) {
+            for (auto &set : cheerEmoteSets)
+            {
                 auto cheerEmoteSet = CheerEmoteSet();
                 cheerEmoteSet.regex = QRegularExpression(
                     "^" + set.prefix.toLower() + "([1-9][0-9]*)$");
```
Comment (fourtf) [inline src/providers/twitch/TwitchChannel.cpp]: QRegularExpression::CaseInsensitiveOption should be used here instead of making it lowercase

File: src/providers/twitch/TwitchChannel.cpp [hunk 3]
```diff
@@ -825,4 +823,48 @@ boost::optional<EmotePtr> TwitchChannel::ffzCustomModBadge() const
...
 }
 
+boost::optional<std::tuple<boost::optional<EmotePtr>, boost::optional<EmotePtr>,
+                           boost::optional<QColor>>>
+    TwitchChannel::cheerEmote(const QString &string)
+{
+    auto sets = this->cheerEmoteSets_.access();
+    for (const auto &set : *sets)
+    {
+        auto match = set.regex.match(string.toLower());
```
Comment (fourtf) [inline src/providers/twitch/TwitchChannel.cpp]: .toLower() can be removed when using QRegularExpression::CaseInsensitiveOption

File: src/widgets/Window.cpp [hunk 4]
```diff
@@ -205,15 +205,317 @@ void Window::addDebugStuff()
...
-    cheerMessages.emplace_back(R"(@badges=;bits=1;color=#FF0000;display-name=?????;emotes=;id=979b6b4f-be9a-42fb-a54c-88fcb0aca18d;mod=0;room-id=11148817;subscriber=0;tmi-sent-ts=1515782819084;turbo=0;user-id=70656218;user-type= :stels_tv!stels_tv@stels_tv.tmi.twitch.tv PRIVMSG #pajlada :trihard1)");
-    cheerMessages.emplace_back(R"(@badges=subscriber/3,premium/1;bits=1;color=#FF0000;display-name=kalvarenga;emotes=;id=4744d6f0-de1d-475d-a3ff-38647113265a;mod=0;room-id=11148817;subscriber=1;tmi-sent-ts=1515782860740;turbo=0;user-id=108393131;user-type= :kalvarenga!kalvarenga@kalvarenga.tmi.twitch.tv PRIVMSG #pajlada :trihard1)");
+    cheerMessages.emplace_back(R"(@badge-info=;badges=bits/1;bits=10;color=#008000;display-name=dGAussie;emotes=;flags=;id=5fb5ed1c-4e18-4a03-9cc7-4a69b7fedff7;mod=0;room-id=11148817;subscriber=0;tmi-sent-ts=1566783370478;turbo=0;user-id=37141440;user-type= :dgaussie!dgaussie@dgaussie.tmi.twitch.tv PRIVMSG #pajlada :Cheer10 W00t podcast)");
```
Comment (fourtf) [inline src/widgets/Window.cpp]: Make a file in the resources containing all those lines and load it using a QFile.

Example for reading line by line: https://stackoverflow.com/questions/5444959/read-a-text-file-line-by-line-in-qt#5445381

Comment (fourtf) [inline src/widgets/Window.cpp]: Put the code that adds into a function in a Header file (not a source file so it doesn't get compiled into the release binary)
