### PR TITLE
Fixed splits staying paused after unfocusing Chatterino in certain configurations

### LINKED ISSUE #5502: Chat pauses after alt-tabbing with "Pause while holding a key: Alt" enabled
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

I have option `Pause while holding a key: Alt` enabled and when I alt-tab from chatterino to another window my chat pauses.
To resume chat auto-scrolling I have to hover over chat my mouse or focus back to it.

I can't really use any other key out of provided options, alt is my only choice.

### Screenshots

Demo: https://kappa.lol/3eSSZ

### OS and Chatterino Version

Chatterino 2.5.1 (commit eafcb941) built with Qt 6.5.0, MSVC 193833135 Running on Windows 10 Version 22H2, kernel: 10.0.19045

### PR DESCRIPTION
**Pull request by Mm2PL**
Fixes #5502.

### CODE REVIEW

**Review by pajlada — APPROVED** [review]

File: src/widgets/splits/Split.hpp [hunk 1]
```diff
@@ -77,6 +77,9 @@ class Split : public BaseWidget
 
     void setInputReply(const MessagePtr &reply);
 
+    // This is called on window focus lost
```
Comment (Nerixyz) [inline src/widgets/splits/Split.hpp:80]: Documentation should say what an entity does, not where it's used. It could say where it's supposed to be used.

**Comment by 00050** [comment]
@Mm2PL Thank you for fixing this  FeelsOkayMan
