### PR TITLE
fix: Display Sent IRC Messages Like Received Ones

### LINKED ISSUE #4020: [IRC] A sent message doesn't look like a received one
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

* The username of the sender isn't colored
* Emojis aren't added as emote elements

I'd like to fix this 🙂 .

I think I'll might fix #3570 on the way since the crash is because `this->server() == nullptr` and it's just a matter of extending the `if`-block:

https://github.com/Chatterino/chatterino2/blob/d9e17e69cff5c1f0259f12d1181d2166ca7dc528/src/providers/irc/IrcChannel2.cpp#L36-L49

### OS and Chatterino Version

Chatterino Nightly 7.3.5 DEBUG (commit 1af89041 modified) built on 2022-09-27 with Qt 5.15.2, Windows SDK, MSVC 192428314

### PR DESCRIPTION
**Pull request by Nerixyz**
Pull request checklist:

- [x] `CHANGELOG.md` was updated, if applicable

# Description

Fixes #4020.

### CODE REVIEW

**Review by pajlada — APPROVED** [review]
Code looks good to me
@Felanbird Could you verify functionality and merge this in?

File: src/providers/irc/IrcChannel2.cpp [hunk 1]
```diff
@@ -33,20 +35,42 @@ void IrcChannel::sendMessage(const QString &message)
...
+                ->setLink({Link::JumpToChannel, this->getName()});
+
+            auto now = QDateTime::currentDateTime();
+            builder.emplace<TimestampElement>(now.time());
+            builder.message().serverReceivedTime = now;
+
+            auto username = this->server()->nick();
+            builder
+                .emplace<TextElement>(
+                    username + ": ", MessageElementFlag::Username,
```
Comment (Felanbird) [inline src/providers/irc/IrcChannel2.cpp:57]:
```suggestion
                    username + ":", MessageElementFlag::Username,
```

**Review by Felanbird — APPROVED** [review]
