### PR TITLE
fix: make QLineEdit's less ugly in light themes

### LINKED ISSUE #6022: QLineEdit is missing styling
### Checklist

- [x] I'm reporting a problem with Chatterino
- [x] I've verified that I'm running **the most** recent nightly build or stable release
- [x] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [x] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

This affects light theme users in the following places:
- Emote search
- Message search
- New split

### Screenshots

Image

### OS and Chatterino Version

Chatterino 2.5.2 (commit 163cb3d82) built with Qt 6.8.2 Running on Arch Linux, kernel: 6.13.4-arch1-1

### PR DESCRIPTION
**Pull request by pajlada**
Fixes #6022

### CODE REVIEW

File: src/widgets/helper/SearchPopup.cpp [hunk 1]
```diff
@@ -212,6 +215,16 @@ bool SearchPopup::eventFilter(QObject *object, QEvent *event)
     return false;
 }
 
+void SearchPopup::themeChangedEvent()
+{
+    BasePopup::themeChangedEvent();
+
+    // NOTE: This currently overrides the QLineEdit's font size.
+    // If the dialog open is when the theme is changed, things will look a bit off.
```
Comment (Nerixyz) [inline src/widgets/helper/SearchPopup.cpp:223]:
```suggestion
    // If the dialog is open when the theme is changed, things will look a bit off.
```

Comment (pajlada) [reply src/widgets/helper/SearchPopup.cpp]: Fixed in [`4df4cb3` (#6055)](https://github.com/Chatterino/chatterino2/pull/6055/commits/4df4cb3eaf756a175ba95c1e6bb781194e69fa2b) - thanks!

**Review by pajlada — COMMENTED** [review]
image
