### PR TITLE
fix: make reply-cancel button less coarse-grained

### LINKED ISSUE #6099: Crunchy reply cancel button
### Checklist

- [x] I'm reporting a problem with Chatterino
- [x] I've verified that I'm running **the most** recent nightly build or stable release
- [x] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [x] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

If you're replying to a message, there's a little cancel bitmap image, which is, since it's a bitmap, kinda crunchy looking. 

I suggest replacing it with an svg icon, such as the Fluent UI filled dismissed circle icon, as (afaik) chatterino already has the license for Fluent UI icons.

<https://github.com/microsoft/fluentui-system-icons/blob/main/assets/Dismiss%20Circle/SVG/ic_fluent_dismiss_circle_48_filled.svg>

### Screenshots

Image

### OS and Chatterino Version

Was a problem while I was running Chatterino on Windows 10 on the `a104a9725efba0b9a6cc738149d7f19661cfd7bb` commit

### PR DESCRIPTION
**Pull request by leungbk**
-------
Fixes #6099.

### CODE REVIEW

File: src/widgets/splits/SplitInput.cpp [hunk 1]
```diff
@@ -303,13 +302,16 @@ void SplitInput::updateCancelReplyButton()
...
+    if (this->theme->isLightTheme())
+    {
+        this->ui_.cancelReplyButton->setSvgResource(":/buttons/cancelDark.svg");
+    }
+    else
+    {
+        this->ui_.cancelReplyButton->setSvgResource(":/buttons/cancel.svg");
+    }
+    this->ui_.cancelReplyButton->setFixedHeight(int(24 * scale));
+    this->ui_.cancelReplyButton->setFixedWidth(int(24 * scale));
```
Comment (pajlada) [inline src/widgets/splits/SplitInput.cpp:314]: We can retain the old size by disabling the margin for now

```suggestion
    this->ui_.cancelReplyButton->setEnableMargin(false);
    this->ui_.cancelReplyButton->setFixedHeight(int(12 * scale));
    this->ui_.cancelReplyButton->setFixedWidth(int(12 * scale));
```

**Review by pajlada — CHANGES_REQUESTED** [review]
Overall looks good, just a nit about the size of the button - try my suggestion & see if that looks as expected for you

As a reference:
Current main branch:
image


Your PR
image

Your PR with my suggestion
image

Might be prudent to try a few more levels of scaling

**Review by Nerixyz — CHANGES_REQUESTED** [review]
On 100% scaling, the button had 4 pixels padding horizontally and no padding vertically:

```diff
diff --git a/src/widgets/helper/Button.cpp b/src/widgets/helper/Button.cpp
index cf941f49c..19c7ec37c 100644
--- a/src/widgets/helper/Button.cpp
+++ b/src/widgets/helper/Button.cpp
@@ -84,7 +84,12 @@ void Button::setSvgResource(const QString &resourcePath)
         return;
     }
 
+    if (this->svgRenderer)
+    {
+        this->svgRenderer->deleteLater();
+    }
     this->svgRenderer = new QSvgRenderer(resourcePath, this);
+    this->svgRenderer->setAspectRatioMode(Qt::KeepAspectRatio);
     this->svgResourcePath = resourcePath;
 
     this->update();
@@ -199,15 +204,7 @@ void Button::paintButton(QPainter &painter)
         if (this->enableMargin_)
         {
             auto s = this->getMargin();
-            auto outSize = rect.size() - QSize{2 * s, 2 * s};
-            outSize = this->svgRenderer->defaultSize().scaled(
-                outSize, Qt::KeepAspectRatio);
-            auto margin = rect.size() - outSize;
-
-            rect = QRect{
-                QPoint{margin.width() / 2, margin.height() / 2},
-                outSize,
-            };
+            rect = {{s, s}, rect.size() - QSize{2 * s, 2 * s}};
         }
 
         this->svgRenderer->render(&painter, rect);
diff --git a/src/widgets/splits/SplitInput.cpp b/src/widgets/splits/SplitInput.cpp
index a8af1c7c7..c2013b44a 100644
--- a/src/widgets/splits/SplitInput.cpp
+++ b/src/widgets/splits/SplitInput.cpp
@@ -310,8 +310,9 @@ void SplitInput::updateCancelReplyButton()
     {
         this->ui_.cancelReplyButton->setSvgResource(":/buttons/cancel.svg");
     }
-    this->ui_.cancelReplyButton->setFixedHeight(int(24 * scale));
-    this->ui_.cancelReplyButton->setFixedWidth(int(24 * scale));
+    this->ui_.cancelReplyButton->setEnableMargin(false);
+    this->ui_.cancelReplyButton->setFixedHeight(int(12 * scale));
+    this->ui_.cancelReplyButton->setFixedWidth(int(20 * scale));
 }
 
 void SplitInput::openEmotePopup()
```

**Review by Nerixyz — APPROVED** [review]

**Review by pajlada — APPROVED** [review]

**Comment by pajlada** [comment]
Thank you! As a first-time contributor, you are now eligible to be listed in the About page in Chatterino.

If you want this, you can open a new PR where you modify the `resources/contributors.txt` file and add yourself to the list. Read the comments at the top for instructions.
