### PR TITLE
Handle ritual (new viewer announcement) messages

### LINKED ISSUE #2689: New viewer "rituals" don't show the user's message
**Describe the bug**
user is new here doesn't show the emote they used for greeting

**Screenshots**
image

**Chatterino version**
Chatterino 2.2.2-fix (commit a82f57f94)

**Operating system**
Windows 10

### PR DESCRIPTION
**Pull request by zneix**
Also a small refactor of how we deduct whether a USERNOTICE message contains user's message in it or not

Pull request checklist:

- [x] `CHANGELOG.md` was updated, if applicable

# Description

pushed to master :tf:

I also created a `QStringList` of message types that can have an extra message provided by the user. Makes following if statement easier.

Closes #2689

### CODE REVIEW

File: src/providers/twitch/IrcMessageHandler.cpp [hunk 1]
```diff
@@ -574,11 +574,18 @@ std::vector<MessagePtr> IrcMessageHandler::parseUserNoticeMessage(
         content = parameters[1];
     }
 
-    if (msgType == "sub" || msgType == "resub" || msgType == "subgift" ||
-        msgType == "bitsbadgetier")
-    {
-        // Sub-specific and bits badge upgrade specific message.
-        // It's only allowed for "resub" messages.
+    // Messages in list below are the ones that might contain special user's message
+    QStringList specialMessageTypes{
```
Comment (leon-richardt) [inline src/providers/twitch/IrcMessageHandler.cpp:578]:
```suggestion
    static const QStringList specialMessageTypes{
```

**Review by leon-richardt — CHANGES_REQUESTED** [review]

File: src/widgets/Window.cpp [hunk 2]
```diff
@@ -211,6 +211,9 @@ void Window::addDebugStuff()
     // resub without message
     subMessages.emplace_back(R"(@badges=subscriber/12;color=#CC00C2;display-name=cspice;emotes=;id=6fc4c3e0-ca61-454a-84b8-5669dee69fc9;login=cspice;mod=0;msg-id=resub;msg-param-months=12;msg-param-sub-plan-name=Channel\sSubscription\s(forsenlol):\s$9.99\sSub;msg-param-sub-plan=2000;room-id=22484632;subscriber=1;system-msg=cspice\sjust\ssubscribed\swith\sa\sTier\s2\ssub.\scspice\ssubscribed\sfor\s12\smonths\sin\sa\srow!;tmi-sent-ts=1528192510808;turbo=0;user-id=47894662;user-type= :tmi.twitch.tv USERNOTICE #pajlada)");
 
+    // viewer ritual message
+    subMessages.emplace_back(R"(@badge-info=;badges=premium/1;color=#4922B2;display-name=winter_styx;emotes=81274:0-5;flags=;id=ad2266af-253c-409b-9131-9bc657773a7a;login=winter_styx;mod=0;msg-id=ritual;msg-param-ritual-name=new_chatter;room-id=143917159;subscriber=0;system-msg=@winter_styx\sis\snew\shere.\sSay\shello!;tmi-sent-ts=1619428046297;user-id=642858998;user-type= :tmi.twitch.tv USERNOTICE #indiefoxx :VoHiYo)");
```
Comment (leon-richardt) [inline src/widgets/Window.cpp:215]: Does it make sense to place this into `subMessages`?

Comment (zneix) [reply src/widgets/Window.cpp:215]: Well it appears as a sub message with the purple background (because of `MessageFlag::Subscription`) so I assumed it fits in there. There's no such category for those special messages with `MessageFlag::Subscription` flag.

Comment (zneix) [reply src/widgets/Window.cpp]: Whatever, I decided to remove it since it's not critically necessary.

File: src/providers/twitch/IrcMessageHandler.cpp [hunk 3]
```diff
@@ -574,11 +574,18 @@ std::vector<MessagePtr> IrcMessageHandler::parseUserNoticeMessage(
         content = parameters[1];
     }
 
-    if (msgType == "sub" || msgType == "resub" || msgType == "subgift" ||
-        msgType == "bitsbadgetier")
-    {
-        // Sub-specific and bits badge upgrade specific message.
-        // It's only allowed for "resub" messages.
+    // Message types below are the ones that might contain special user's message
+    static const QStringList specialMessageTypes{
```
Comment (pajlada) [inline src/providers/twitch/IrcMessageHandler.cpp:578]: Please switch this out from a `QStringList` to a `QSet`

**Review by pajlada — CHANGES_REQUESTED** [review]

**Review by pajlada — APPROVED** [review]

**Comment by pajlada** [comment]
:+1: LGTM - Will resolve conflicts and merge in later

**Review by pajlada — APPROVED** [review]
