### PR TITLE
Change sound backend from Qt to miniaudio

### LINKED ISSUE #1228: 🚫🎵 No Sound from Pings🎵🚫
**Describe the bug**

Ping sounds don't generate a noise

**To Reproduce**

This issue was referenced to me by another person so I recreated it by doing this:

I downloaded the newest nightly and added a portable folder (as to not add any settings), added my account, added (and subsequently disabled) an extra highlight of my username for testing, and pinged my username via another chatterino instance + account, and no sound was generated.

**Expected behavior**

Ping sound to make a noise.

**Screenshots**

https://streamable.com/ex5qg
Commit on 2nd instance covered by box is https://github.com/Chatterino/chatterino2/commit/cbd93f95374d2377b21f2386fb47c8f6c517f45b

**Chatterino version**

Chatterino Nightly 2.1.0 (21.08.2019 3079765)

**Additional context**

I use multiple instances of chatterino normally, a forked version of https://github.com/Chatterino/chatterino2/commit/feef6c6aaa9ed7c250a818272c6da7eef612e550 & https://github.com/Chatterino/chatterino2/commit/cbd93f95374d2377b21f2386fb47c8f6c517f45b both of these instances have no ping problems at all.

I also tested on 381aaaa and I thought it generated the same issue as 3079765 but after closing OBS I was unable to recreate the issue with this instance, even with reopening OBS and recording with it. 

I think this issue involves the fact that 3079765 doesn't show up on volume mixer , as the person who referenced this issue to me mentioned the same problem. 
I do personally use VoiceMeeter Banana to keep discord out of OBS but the person who referenced me this does not use any sound alteration programs (that he knows of).

Myself and the person who referenced this are both on Windows Version 1903 (OS Build 18362.295) , and I was forcibly updated to this version a few days ago actually. 😤

I closed the normal gaming issue suspects, Battle.net/Steam/Discord , included a PC restart. 
I think this is probably a windows side issue but I tried my best. /shrug

### LINKED ISSUE #1406: If chatterino tries to play notification for file that doesn't exist, one thread deadlocks
**Describe the bug**
If you have notifications for when streamer goes live and you have a sound set that does not exist in set path, chatterino will have a thread that will deadlock and eat all CPU for one core

**To reproduce**
Set up notifications for some streamers, set a custom sound, turn off chatterino, edit the sound path in config file to non-existent one, wait for streamer to go live.

**Chatterino version**
Chatterino Nightly 2.1.5 (commit 556c2aef2, 02.11.2019)

**Operating system**
Win 10 1903 18362.356

### LINKED ISSUE #1736: Highlight sound repeats despite only being triggered once
**Describe the bug**

can keep pinging even in focus
**To reproduce**

get a ping, wait
**Screenshots**

https://streamable.com/ihb7y3
**Chatterino version**

Chatterino 2.1.7 (commit 845c8fa63)
**Operating system**

win.10
**Additional information**

### LINKED ISSUE #2056: No Highlight Sound on Linux Mint
**Describe the bug**

No sound is played on a highlight, tested it on two different systems running Linux Mint 20 and deleted all Settings.
I also tested adding a custom sound.
It's not even displaying in "Applications playing" in the Sound Settings.
I don't remember when it started playing no sound, but I think at least since version 2.2.0 

**To reproduce**

Run Chatterino on Linux Mint 20 and get highlighted

**Screenshots**

**Chatterino version**

Chatterino 2.2.2 (commit 98762fdfa, 10.10.2020) using the AppImage

**Operating system**

OS: Linux Mint 20 x86_64
Kernel: 5.4.0-48-generic

**Additional information**

### LINKED ISSUE #3560: Highlight sound delay for first highlight after application start
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

When chatterino is started, the first highlight can have a noticeable delay before showing & playing sound. I've seen it show up in webchat before chatterino multiple times.

### Screenshots

Unable to reproduce consistently, but will attempt to record each time I open chatterino.

### OS and Chatterino Version

Chatterino 2.3.4 (commit 5490ff50) & Chatterino 7.3.4 (commit 33a8bd48) on Arch Linux (5.16.5), bspwm, Pipewire for audio

### LINKED ISSUE #3807: Not getting sound notification when I am pinged
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

Hey,

I've just had issues getting a ping sound when I'm tagged in the chat, both with my username and any nicknames. I believe this started happening when I updated my chatterino to 7.3.5 (from an original version that didn't include 7tv emotes), and it's just been very random. I did see that from previous threads there was some underlying problem that makes Chatterino not appear in the Volume Mixer, and that is true for me as well. I haven't seen anything else that has gotten a solution but if there's any kind of other details I need to include or if there's anything anyone would recommend, I'd be happy to do either. Thanks.

### Screenshots

image

### OS and Chatterino Version

Chatterino 7.3.5 (commit 132b406cc), Windows 10 Version 21H2

### LINKED ISSUE #3823: Highlight sounds "queue up" before all playing in rapid sucession
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

When I am highlighted and a sound should play, there's a 90% chance I won't hear anything. From that point onwards the pings "queue up" until they eventually all play in rapid succession. This can be anywhere between a few minutes after to a few hours.

Have not tested on c2 yet but I do not believe this to be a c7-specific bug. Will attempt to test with c2

### Screenshots

_No response_

### OS and Chatterino Version

Chatterino 7.3.5 DEBUG (commit 652859cc) built with Qt 5.15.4 Running on Arch Linux, kernel: 5.18.3-zen1-1-zen

### PR DESCRIPTION
**Pull request by pajlada**
Pull request checklist:

- [x] `CHANGELOG.md` was updated, if applicable

# Description

- Use miniaudio for playing highlights
- Use miniaudio for playing "going live" notifications
- Remove QMediaPlayer includes

# How to test

1. Open Chatterino
2. Before you receive any mentions, ensure Chatterino shows up in your OS volume mixer. Please screenshot this.
3. Have a mention sound play without a custom sound selected. You should hear the default Chatterino ping. Test this at least 5 times.
4. Set a custom sound either for your highlight or a default fallback sound. Have a mention fire. You should hear the custom sound play. Test this at least 5 times.
5. Remove the custom sound, then have a mention fire again. You should hear the default Chatterino ping.
6. If your volume mixer supports this, reduce the volume of Chatterino, shut down Chatterino, open up Chatterino again and ensure the volume you changed is saved.

 - [x] Linux with pulseaudio
 - [x] Linux with pipewire
 - [x] macos
 - [x] windows

Fixes #2056 - GStreamer is no longer a dependency so AppImages should always have sound as long as they have alsa or pulseaudio or OSS available.
Fixes #3823 - We don't rely on QtMultimedia anymore.
Fixes #3807 - High confidence level
Fixes #3560 - the sound device & engine is created once on startup.
Fixes #1736
Fixes #1228
Fixes #1406

### CODE REVIEW

**Comment by pajlada** [comment]
Arch Linux btw, Qt 5.15.8, standard pulseaudio setup
Volume mixer before any sound plays
image
Default sound into custom sound into default sound works as expected
Volume mixer saves the volume as expected

Changes I noticed: This miniaudio branch plays sounds at a sliiiiiiightly lower volume.

**Comment by Yoitsu** [comment]
Arch Linux (btw), Pipewire with pipewire-pulseaudio
image

Everything tested worked as expected

**Comment by Nerixyz** [comment]
**Windows 10**

2. ✅ Shows up before playing any sound<details>
    <summary>Screenshot</summary>
    
    SndVol_2023-01-28_12-48-33
    </details>
3. ❌ Playing a custom sound doesn't work. Tried: [sounds.zip](https://github.com/Chatterino/chatterino2/files/10527163/sounds.zip) (zipped because GitHub doesn't allow uploading mp3/wav files)
4. ✅ Works
5. ✅ Works

**Comment by pajlada** [comment]
I can confirm the sounds from your zip file work as expected on Linux

**Comment by pajlada** [comment]
intel mac 2020, macOS 12.6 monterey
Tested default & custom sounds (wav & mp3), works as expected :+1: Thanks helmak

**Comment by pajlada** [comment]
Custom sounds work on Windows after the latest commit

File: src/controllers/sound/SoundController.cpp [hunk 1]
```diff
@@ -0,0 +1,195 @@
...
+
+#define MINIAUDIO_IMPLEMENTATION
+#include <miniaudio.h>
+
+#include <limits>
+#include <memory>
+
+namespace chatterino {
+
+constexpr const auto NUM_SOUNDS = 4;
```
Comment (pajlada) [inline src/controllers/sound/SoundController.cpp:16]: Add a comment here

File: src/controllers/sound/SoundController.cpp [hunk 2]
```diff
@@ -0,0 +1,195 @@
...
+
+SoundController::SoundController()
+    : context(std::make_unique<ma_context>())
+    , resourceManager(std::make_unique<ma_resource_manager>())
+    , device(std::make_unique<ma_device>())
+    , engine(std::make_unique<ma_engine>())
+{
+}
+
+// TODO: How do we know what the default ping sound is?
```
Comment (pajlada) [inline src/controllers/sound/SoundController.cpp:26]: Remove this comment

File: src/controllers/sound/SoundController.cpp [hunk 3]
```diff
@@ -0,0 +1,195 @@
...
+            // This must match the encoding format of our default ping sound
+            decoderConfig.encodingFormat = ma_encoding_format_wav;
+
+            auto dec = std::make_unique<ma_decoder>();
+            auto snd = std::make_unique<ma_sound>();
+
+            result = ma_decoder_init_memory(
+                (void *)this->defaultPingData.data(),
+                this->defaultPingData.size() * sizeof(char), &decoderConfig,
+                dec.get());
```
Comment (pajlada) [inline src/controllers/sound/SoundController.cpp:122]: Check result

File: src/controllers/sound/SoundController.cpp [hunk 4]
```diff
@@ -0,0 +1,195 @@
...
+
+            result = ma_sound_init_from_data_source(
+                this->engine.get(), dec.get(),
+                MA_RESOURCE_MANAGER_DATA_SOURCE_FLAG_DECODE, nullptr,
+                snd.get());
```
Comment (pajlada) [inline src/controllers/sound/SoundController.cpp:127]: Check result

File: src/controllers/sound/SoundController.cpp [hunk 5]
```diff
@@ -0,0 +1,195 @@
...
+
+            this->defaultPingDecoders.emplace_back(std::move(dec));
+            this->defaultPingSounds.emplace_back(std::move(snd));
+        }
+
+        qCDebug(chatterinoSound) << "init sound! ";
```
Comment (pajlada) [inline src/controllers/sound/SoundController.cpp:133]: Remove this debug

File: src/controllers/sound/SoundController.cpp [hunk 6]
```diff
@@ -0,0 +1,195 @@
...
+    }
+
+    this->initialized = true;
+}
+
+SoundController::~SoundController()
+{
+    for (const auto &snd : this->defaultPingSounds)
```
Comment (pajlada) [inline src/controllers/sound/SoundController.cpp:141]: Add comment here stating that this destructor is never called but it has been called & tested manually during development

File: src/controllers/sound/SoundController.cpp [hunk 7]
```diff
@@ -0,0 +1,195 @@
...
+    {
+        ma_sound_uninit(snd.get());
+    }
+    this->defaultPingSounds.clear();
```
Comment (pajlada) [inline src/controllers/sound/SoundController.cpp:145]: Remove clear

File: src/controllers/sound/SoundController.cpp [hunk 8]
```diff
@@ -0,0 +1,195 @@
...
+    for (const auto &dec : this->defaultPingDecoders)
+    {
+        ma_decoder_uninit(dec.get());
+    }
+    this->defaultPingDecoders.clear();
```
Comment (pajlada) [inline src/controllers/sound/SoundController.cpp:150]: Remove clear

File: src/controllers/sound/SoundController.cpp (hunk 1 above)
Comment (pajlada) [reply src/controllers/sound/SoundController.cpp:17]: Resolved in [`bed44d1` (#4334)](https://github.com/Chatterino/chatterino2/pull/4334/commits/bed44d18a311db365d0b706dc93ec32e3564f69f)

File: src/controllers/sound/SoundController.cpp (hunk 2 above)
Comment (pajlada) [reply src/controllers/sound/SoundController.cpp]: Resolved in [`bed44d1` (#4334)](https://github.com/Chatterino/chatterino2/pull/4334/commits/bed44d18a311db365d0b706dc93ec32e3564f69f)

File: src/controllers/sound/SoundController.cpp (hunk 3 above)
Comment (pajlada) [reply src/controllers/sound/SoundController.cpp:122]: Resolved in [`bed44d1` (#4334)](https://github.com/Chatterino/chatterino2/pull/4334/commits/bed44d18a311db365d0b706dc93ec32e3564f69f)

File: src/controllers/sound/SoundController.cpp (hunk 4 above)
Comment (pajlada) [reply src/controllers/sound/SoundController.cpp:134]: Resolved in [`bed44d1` (#4334)](https://github.com/Chatterino/chatterino2/pull/4334/commits/bed44d18a311db365d0b706dc93ec32e3564f69f)

File: src/controllers/sound/SoundController.cpp (hunk 5 above)
Comment (pajlada) [reply src/controllers/sound/SoundController.cpp]: Resolved in [`bed44d1` (#4334)](https://github.com/Chatterino/chatterino2/pull/4334/commits/bed44d18a311db365d0b706dc93ec32e3564f69f)

File: src/controllers/sound/SoundController.cpp (hunk 6 above)
Comment (pajlada) [reply src/controllers/sound/SoundController.cpp:158]: Resolved in [`bed44d1` (#4334)](https://github.com/Chatterino/chatterino2/pull/4334/commits/bed44d18a311db365d0b706dc93ec32e3564f69f)

File: src/controllers/sound/SoundController.cpp (hunk 7 above)
Comment (pajlada) [reply src/controllers/sound/SoundController.cpp]: Resolved in [`bed44d1` (#4334)](https://github.com/Chatterino/chatterino2/pull/4334/commits/bed44d18a311db365d0b706dc93ec32e3564f69f)

Comment (pajlada) [reply src/controllers/sound/SoundController.cpp]: Resolved in [`bed44d1` (#4334)](https://github.com/Chatterino/chatterino2/pull/4334/commits/bed44d18a311db365d0b706dc93ec32e3564f69f)

File: src/controllers/sound/SoundController.cpp (hunk 8 above)
Comment (pajlada) [reply src/controllers/sound/SoundController.cpp]: Resolved in [`bed44d1` (#4334)](https://github.com/Chatterino/chatterino2/pull/4334/commits/bed44d18a311db365d0b706dc93ec32e3564f69f)

**Comment by pajlada** [comment]
Letting this PR brew until tomorrow in case anyone else wants to sanity-check my code. Hopefully I've made everything clear enough, the miniaudio API is fairly simple but let me know if you have any questions.

**Comment by pajlada** [comment]
After this PR, we don't have any dependency on `gst` stuff

**Comment by pajlada** [comment]
[`35d0387` (#4334)](https://github.com/Chatterino/chatterino2/pull/4334/commits/35d03872765ec7f88c8b92dfbc8a9cb36583e6b9) fixes the audio levels being lower with this PR

**Comment by Greenlandicsmiley** [comment]
Since this PR changes how highligh sounds are played, there are some issues that get fixed, or need to be looked at again.

**Linux issues that get fixed**

#2056 The AppImage issue is fixed with GStreamer gone as a dependency.

#3823 Sounds no longer queue up with Qt Multimedia gone.

**Issues that need to be looked at again**

#3807 Likely fixed. Chatterino appears in volume mixer as soon as it is started.

#3560 Likely fixed.

#1736 Likely fixed.

#1228 Likely fixed, I tried opening 8 instances of Chatterino on Windows, they all show up in volume mixer as soon as Chatterino started and they all play a highlight sound.

**Comment by Felanbird** [comment]
If we are able to fix this many issues with this change, we likely should also have a minor entry 
`Bugfix: Attempt to fix the most common audio issues on Windows & Linux (#4334)`

**Review by pajlada — COMMENTED** [review]
Looks good to me!
image
