### PR TITLE
fix: get rid of duplicate scale events

### LINKED ISSUE #1266: Tabs are too wide after changing zoom
**Describe the bug**

After resetting the zoom some elements are misplaced and some others have size problems.

**How to Reproduce**

Zoom Chatterino as far as you can by holding control and scrolling up. Press Ctrl+0 to reset the zoom. Text boxes will be bigger than normal, tab headers will be bigger than needed, hints where the subs/notifs are will be moved towards the middle.

**Expected behavior**

The zoom will be reset like it is done with scrolling the wheel.

**Screenshots**

screenshot

**Chatterino version**

2.1.2 671c9ed
Edit: stupid mistake

**Additional context**

If you change the zoom by ctrl scrolling the wheel everything will be back to normal.

### PR DESCRIPTION
**Pull request by Nerixyz**
Previously, two scale events were emitted to fix #1266. This PR fixes #1266 by introducing `NotebookTab::normalTabWidthForHeight` which computes the width for the height _after_ scaling (in `NotebookTab::updateSize`). This would previously require two invocations (first one to set the height and second one the width). Furthermore, it gets rid of refreshing the notebook too often (~> performing layout for every tab).

As a next step, this PR checks if the scale has changed at all in `BaseWidget::setScale`. This will probably introduce some bugs, but I think it's better to address these individually instead of spamming scale events (like I did for SplitHeader).

### CODE REVIEW

File: src/widgets/dialogs/SettingsDialog.cpp [hunk 1]
```diff
@@ -397,12 +397,8 @@ void SettingsDialog::refresh()
     }
 }
 
-void SettingsDialog::scaleChangedEvent(float newDpi)
+void SettingsDialog::scaleChangedEvent(float /*newScale*/)
 {
-    assert(newDpi == 1.F &&
-           "Scaling is disabled for the settings dialog - its scale should "
-           "always be 1");
```
Comment (pajlada) [inline src/widgets/dialogs/SettingsDialog.cpp:404]: Why is this assert removed?

**Review by pajlada — COMMENTED** [review]
Overall looks good, will test & look a bit closer tomorrow

**Review by pajlada — APPROVED** [review]
