### PR TITLE
Fixed the first link being broken in `/mods` and `/vips`

### LINKED ISSUE #3345: Leading space in first user listed in /mods & /vips
**Describe your issue**

After #3187 added the functionality to click the users listed in /mods & /vips, I noticed that the very first user listed does not load, and the login name is very slightly off centered. After looking into this I saw that there is a leading space for the very first user.

**Screenshots**
image
image

**OS and Chatterino Version**
All versions after 5f7caebce0e48f42fd038d4b7fbfd0cd6cf5f66e

### PR DESCRIPTION
**Pull request by Mm2PL**
Pull request checklist:

- [x] `CHANGELOG.md` was updated, if applicable

# Description

Closes #3345

### CODE REVIEW

File: src/providers/twitch/TwitchMessageBuilder.cpp [hunk 1]
```diff
@@ -1452,7 +1452,7 @@ void TwitchMessageBuilder::modsOrVipsSystemMessage(QString prefix,
     builder->emplace<TimestampElement>();
     builder->message().flags.set(MessageFlag::System);
     builder->message().flags.set(MessageFlag::DoNotTriggerNotification);
-    builder->emplace<TextElement>(prefix, MessageElementFlag::Text,
+    builder->emplace<TextElement>(prefix + " ", MessageElementFlag::Text,
```
Comment (Felanbird) [inline src/providers/twitch/TwitchMessageBuilder.cpp:1455]:
```suggestion
    builder->emplace<TextElement>(prefix, MessageElementFlag::Text,
```

image - current
vs
image - change

File: CHANGELOG.md [hunk 2]
```diff
@@ -51,6 +51,7 @@
 - Bugfix: Fixed the reconnection backoff accidentally resetting when thrown out of certain IRC servers. (#3328)
 - Bugfix: Fixed underlying text from disabled emotes not being colorized properly. (#3333)
 - Bugfix: Fixed IRC ACTION messages (/me) not being colorized properly. (#3341)
+- Bugfix: Fixed the first link being broken in `/mods` and `/vips` (#3349)
```
Comment (Felanbird) [inline CHANGELOG.md:54]:
```suggestion
- Bugfix: Fixed the first usercard being broken in `/mods` and `/vips` (#3349)
```

**Review by Felanbird — CHANGES_REQUESTED** [review]

**Review by Felanbird — APPROVED** [review]
Functionality works as intended. 👍

**Review by pajlada — APPROVED** [review]
