### PR TITLE
Made #channel link in /mentions jump to #channel split

### LINKED ISSUE #2087: When channel name of a mention is clicked, two broken webpages open
**Describe the bug**
Double clicking on the channel name to the left of a message in the /mentions channel opens two web pages. One is just the name of the channel and the other appears to be a guid. Neither are real sites.

**To reproduce**
Double click the channel name to the left of a mention message

**Screenshots**
image

**Chatterino version**
Chatterino 2.2.2 (commit 07fc0c3ad)
Chatterino Nightly 2.2.2 (commit 48a3506d7, 17.10.2020)

**Operating system**
Windows 10

### PR DESCRIPTION
**Pull request by zneix**
Pull request checklist:

- [x] `CHANGELOG.md` was updated, if applicable

# Description

The `#channel` part in `/mentions` tab is a link and as fourtf once said, it was supposed to take you to the channel and message that you were mentioned in - very similar to how it is done on Discord, but it wasn't working properly and even shown those bugged URL links on some environments (See #2087).

I looked at code from channel switcher and in a pretty similar way added it here. And while channel switcher opens up a new channel when the target channel is closed, I assumed that messages in `/mentions` come always from already open channels and there's no real need to make this function open a new channel because I assume that the split with a channel will still be open.

While switching current SplitContainer and the Split itself works flawlessly, I wasn't really able to implement scrolling to certain message - maybe I can look into that further in the future and send another PR with the solution, but for now this is better than nothing and also fixes an open issue.

<details>
<summary>GIF with demonstration</summary>

</details>

Closes #2087

### CODE REVIEW

**Comment by leon-richardt** [comment]
Now that we use this in multiple places, it might make sense to provide the [`openPages()`](https://github.com/Chatterino/chatterino2/blob/05aab868455500ede7cc1d3d3f9a2006392d5f12/src/widgets/dialogs/switcher/QuickSwitcherPopup.cpp#L19-L30) functionality in some public interface.

(Not sure if appropriate for this PR but just something to keep in mind.)

**Comment by zneix** [comment]
> Not sure if appropriate for this PR

I think that's appropriate, since I've made use of this method and we might as well refactor that to some publicly available function because I bet it might be used somewhere else as well.
I will try something and if that's not okay, I can always revert it.

File: src/widgets/helper/ChannelView.cpp [hunk 1]
```diff
@@ -2043,6 +2043,41 @@ void ChannelView::handleLinkClick(QMouseEvent *event, const Link &link,
...
+            QSet<SplitContainer *> openPages;
+
+            auto &nb = getApp()->windows->getMainWindow().getNotebook();
+            for (int i = 0; i < nb.getPageCount(); ++i)
+            {
+                openPages.insert(
+                    static_cast<SplitContainer *>(nb.getPageAt(i)));
+            }
+
+            for (auto *sc : openPages)
```
Comment (pajlada) [inline src/widgets/helper/ChannelView.cpp:2057]: please rename `sc` to `page`

File: src/widgets/helper/ChannelView.cpp [hunk 2]
```diff
@@ -2043,6 +2043,41 @@ void ChannelView::handleLinkClick(QMouseEvent *event, const Link &link,
...
+                    });
+
+                if (it != splits.end())
+                {
+                    // Select SplitContainer and Split itself where mention message was sent
+                    // TODO(zneix): Try exploring ways of scrolling to a certain message as well
+                    auto &nb = getApp()->windows->getMainWindow().getNotebook();
+                    nb.select(sc);
+
+                    Split *dankSplit = *it;
```
Comment (pajlada) [inline src/widgets/helper/ChannelView.cpp:2075]: please rename `dankSplit` to `split`

File: src/widgets/helper/ChannelView.cpp [hunk 3]
```diff
@@ -2043,6 +2043,41 @@ void ChannelView::handleLinkClick(QMouseEvent *event, const Link &link,
...
+            {
+                openPages.insert(
+                    static_cast<SplitContainer *>(nb.getPageAt(i)));
+            }
+
+            for (auto *sc : openPages)
+            {
+                auto splits = sc->getSplits();
+
+                // Find channel with mention in all opened channels
```
Comment (pajlada) [inline src/widgets/helper/ChannelView.cpp:2061]: Update comment phrasing a bit, maybe something along the lines of:
`Search for channel matching link in page/split container`

**Review by pajlada — CHANGES_REQUESTED** [review]

File: src/widgets/helper/ChannelView.cpp (hunk 1 above)
Comment (zneix) [reply src/widgets/helper/ChannelView.cpp]: Updated in 012f98be

File: src/widgets/helper/ChannelView.cpp (hunk 2 above)
Comment (zneix) [reply src/widgets/helper/ChannelView.cpp]: Renamed in 012f98be

File: src/widgets/helper/ChannelView.cpp (hunk 3 above)
Comment (zneix) [reply src/widgets/helper/ChannelView.cpp]: Fixed in 012f98be
