### PR TITLE
fix: don't include blocked users in join/part messages

### LINKED ISSUE #2505: Ignore does not hide join/parts in channel
**What should be added?**
Not sure if this is implemented in any way, but i ignored maybe 10-20 bots that regularly join/part most twitch channels but can still see their joins and leaves. Assuming ignore is just to not see their messages.

**Why should it be added?**
Hides clutter that is not needed to see in chat.

### PR DESCRIPTION
**Pull request by pajlada**
Users who are blocked no longer show up in the "Users joined:" or "Users parted:" messages

Fixes #2505

The biggest chunk of code of this fix comes from adding user logins to the list of blocks. There are some container types that allow for use of multiple keys (basically keeping the same type of logic we use with multiple sets but internally instead), but that seemed a bit out of scope of this change.

### CODE REVIEW

File: src/providers/twitch/TwitchAccount.cpp [hunk 1]
```diff
@@ -138,51 +140,60 @@ void TwitchAccount::loadBlocks()
...
 {
     assertInGuiThread();
     assert(getApp()->isTest());
 
     TwitchUser blockedUser;
     blockedUser.id = userID;
+    blockedUser.name = userLogin;
     this->ignores_.insert(blockedUser);
     this->ignoresUserIds_.insert(blockedUser.id);
+    this->ignoresUserIds_.insert(blockedUser.name);
```
Comment (Nerixyz) [inline src/providers/twitch/TwitchAccount.cpp:196]:
```suggestion
    this->ignoresUserLogins_.insert(blockedUser.name);
```

**Review by Nerixyz — CHANGES_REQUESTED** [review]

File: src/providers/twitch/TwitchAccount.cpp (hunk 1 above)
Comment (pajlada) [reply src/providers/twitch/TwitchAccount.cpp]: Fixed in 59b163b91b3c2f81252a7319767bb024e1b1f518

File: src/common/ChannelChatters.cpp [hunk 2]
```diff
@@ -27,8 +31,18 @@ void ChannelChatters::addRecentChatter(const QString &user)
...
-    joinedUsers->append(user);
+    assertInGuiThread();
+
+    if (getApp()
+            ->getAccounts()
+            ->twitch.getCurrent()
+            ->blockedUserLogins()
+            .contains(user))
+    {
+        return;
```
Comment (iProdigy) [inline src/common/ChannelChatters.cpp:42]: imo moderator status should override & show join/part, even if user was blocked

Comment (iProdigy) [reply src/common/ChannelChatters.cpp:41]: Done in https://github.com/Chatterino/chatterino2/pull/6181/commits/f805385655844209bc2516a1f2e6d125774b60db thanks!

**Review by pajlada — COMMENTED** [review]
image
