### PR TITLE
fix: use the full url when resolving

### LINKED ISSUE #5343: Unable to open links without protocol
### Checklist

- [X] I'm reporting a problem with Chatterino
- [X] I've verified that I'm running **the most** recent nightly build or stable release
- [X] I've looked for my problem on the [wiki](https://wiki.chatterino.com/Help/)
- [X] I've searched the [issues and pull requests](https://github.com/Chatterino/chatterino2/issues?q=) for similar looking reports

### Describe your issue

I can't open links that don't have a protocol (http/https). I can click them, but nothing happens.

Links that work:
http://www.google.com
https://www.google.com

Links that do not work:
www.google.com
google.com

The link preview also does not work for these links.

image

### Screenshots

_No response_

### OS and Chatterino Version

Chatterino 2.5.0 DEBUG (commit 1a04bda5 modified) built with Qt 5.15.13 Running on Arch Linux, kernel: 6.8.5-arch1-1

### PR DESCRIPTION
**Pull request by Nerixyz**
The link passed to the link resolver is the one that ends up in the return value of `getLink()` (if it wasn't resolved in the meantime).

Calling `setLink` on a `LinkElement` doesn't actually do anything, because it provides its own `getLink`.

Fixes #5343.

<sub>voting for a patch release this week</sub>

### CODE REVIEW

File: tests/src/LinkParser.cpp [hunk 1]
```diff
@@ -173,3 +176,80 @@ TEST(LinkParser, doesntParseInvalidLinks)
...
+                << input.toStdString() << ": "
+                << p.result()->rest.toString().toStdString()
+                << " != " << expectedResult->rest.toString().toStdString();
+            ASSERT_EQ(p.result()->source, expectedResult->source)
+                << input.toStdString() << ": "
+                << p.result()->source.toStdString()
+                << " != " << expectedResult->source.toStdString();
+        }
+    }
+}
```
Comment (Nerixyz) [inline tests/src/LinkParser.cpp:255]: Why are these tests separate? All of them have the property that `source == protocol + host + rest`. If the input should be printed in the assertion, this should be added in `Check::check`.

Comment (pajlada) [reply tests/src/LinkParser.cpp:255]: When reading through the tests, this was not immediately clear to me. Having an explicit input & expected output from a test makes it clearer. I understand this does not hit any paths that weren't hit before.

If you want I can move these tests into a separate PR

**Review by pajlada — APPROVED** [review]
