### PR TITLE
fix: removed EventSub opt in settings

### LINKED ISSUE #6899: Remove EventSub opt in setting
the "Enable experimental Twitch EventSub support" setting should be removed and users should always connect to Twitch EventSub.

### PR DESCRIPTION
**Pull request by nemida**
Removed UI Checkbox
Removed the definition in Settings.hpp
Made it so that it connects to Twitch EventSub unconditionally.
Fixes #6899

### CODE REVIEW

File: src/singletons/Settings.hpp [hunk 1]
```diff
@@ -803,12 +803,6 @@ class Settings
         false,
     };
 
-    // Advanced
```
Comment (Wissididom) [inline src/singletons/Settings.hpp:806]: Shouldn't this comment stay?

File: src/Application.cpp [hunk 2]
```diff
@@ -130,14 +130,7 @@ SeventvEventAPI *makeSeventvEventAPI(Settings &settings)
...
 eventsub::IController *makeEventSubController(Settings &settings)
 {
-    bool enabled = settings.enableExperimentalEventSub;
-
-    if (enabled)
-    {
-        return new eventsub::Controller();
-    }
-
-    return new eventsub::DummyController();
```
Comment (Wissididom) [inline src/Application.cpp:140]: Would it cause any problem removing the DummyController alltogether if it isn't being used somewhere else?

File: src/singletons/Settings.hpp (hunk 1 above)
Comment (nemida) [reply src/singletons/Settings.hpp:806]: Yes, my bad.

File: src/Application.cpp (hunk 2 above)
Comment (nemida) [reply src/Application.cpp:140]: I don't think so. I'll remove it in the next commit.

File: src/Application.cpp [hunk 3]
```diff
@@ -130,14 +130,7 @@ SeventvEventAPI *makeSeventvEventAPI(Settings &settings)
...
+    return new eventsub::Controller();
```
Comment (pajlada) [inline src/Application.cpp]: You can remove the `makeEventSubController` too and create it inside the Application constructor instead, similar to `Logging` and `Fonts` above it

**Review by pajlada — APPROVED** [review]

**Comment by pajlada** [comment]
Thank you! As a first-time contributor, you are now eligible to be listed in the About page in Chatterino.

If you want this, you can open a new PR where you modify the `resources/contributors.txt` file and add yourself to the list. Read the comments at the top for instructions.
